name: warung_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:

  pdf: ^3.10.8
  printing: ^5.12.0
  share_plus: ^9.0.0

  # Flutter SDK
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.5

  # Database Lokal
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.3

  # Ambil Gambar
  image_picker: ^1.1.2

  # Utility
  intl: ^0.19.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Kode Generator WAJIB DI SINI
  build_runner: ^2.4.11
  isar_generator: ^3.1.0+1

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true